namespace :my_task do
  desc 'テスト用のタスクです'
  task :hello_world do
    puts 'hello world!'
  end
end

require 'rake/testtask'

Rake::TestTask.new do |t|
  t.pattern = 'test/**/*_test.rb'
end

task default: :test
